Add `refStatuses` CEL variable
DeterminateSystems/flake-checker pull request #151
Opened 2024-12-18 17:33 UTC by Jayman2000

This pull request allows you to filter Nixpkgs branches by status. For example, you could run the following command if you wanted Nix Flake Checker to give you an error if detects a deprecated branch:

```bash
flake-checker --condition "supportedRefs.contains(gitRef) && refStatuses[gitRef] != 'deprecated'"
```

See the commit messages for details.

2025-01-06 14:26 UTC, lucperkins requested changes
Looks good to me! Very cool. Thanks so much for taking the time to put this together. My one request is that you update the `ref-statuses.json` again just to make sure there hasn't been significant drift in the past few weeks. Once you've updated that or verified that there are no changes, this is good to go.

2025-01-06 19:02 UTC, Jayman2000 commented
> Looks good to me! Very cool. Thanks so much for taking the time to put this together. My one request is that you update the `ref-statuses.json` again just to make sure there hasn't been significant drift in the past few weeks. Once you've updated that or verified that there are no changes, this is good to go.

Awesome! I just pushed a new version of this PR with the following changes:

- `ref-statuses.json` has been updated to account for the fact that the 24.05 branches are now unmaintained. Previously, they were deprecated.
- I added a new commit titled “Preemptively fix outdated test”.

2025-01-06 19:03 UTC, lucperkins approved these changes

2025-01-08 17:16 UTC, lucperkins commented
@Jayman2000 One last very annoying thing: could you run `nix flake update`? The current `flake.lock` is now out of date. Oh, the delicious irony... 😄

2025-01-08 18:42 UTC, Jayman2000 commented
> @Jayman2000 One last very annoying thing: could you run `nix flake update`? The current `flake.lock` is now out of date. Oh, the delicious irony... 😄

Done.

2025-01-09 14:11 UTC, merged